# Generated by Django 6.0.3 on 2026-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
